Update to v2.0.8
CentOS-Storage-SIG/gdeploy pull request #2
Opened 2018-04-24 11:19 UTC by ramkrsna

- PR for new version of gdeploy

2018-05-07 08:39 UTC, sandrobonazzola approved these changes

2018-05-07 08:56 UTC, sandrobonazzola commented on gdeploy.spec
> +%py2_build
%if 0%{?with_doc} has been removed, causing the following %endif to be without an %if

2018-05-07 08:56 UTC, sandrobonazzola requested changes
See inline comments

2018-05-30 15:29 UTC, nixpanic requested changes
See Sandros comment, the `%endif` needs to be removed.

2018-05-31 15:41 UTC, closed without merging